services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    shm_size: ${SIZE}
    volumes:
      - pgdata:${PGDATA}
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password@123"
    ports:
      - 5432:5432
    networks:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256m
networks:
  postgres:
    driver: bridge
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMEPATH}
      o: bind
