version: "3.9"

services:
  mssql:
    container_name: mssql
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ${VOLUMEPATH}/mssql/data:/var/opt/mssql/data
      - ${VOLUMEPATH}/mssql/log/log:/var/opt/mssql/log
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin@123"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - 1455:1433
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
